[2025-01-28T23:52:03.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T23:52:03.604+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_2 manual__2025-01-28T23:52:01.779071+00:00 [queued]>
[2025-01-28T23:52:03.611+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_2 manual__2025-01-28T23:52:01.779071+00:00 [queued]>
[2025-01-28T23:52:03.612+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T23:52:03.622+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_values_2> on 2025-01-28 23:52:01.779071+00:00
[2025-01-28T23:52:03.626+0000] {standard_task_runner.py:72} INFO - Started process 1172 to run task
[2025-01-28T23:52:03.629+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_2', 'manual__2025-01-28T23:52:01.779071+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpt9vbybqe']
[2025-01-28T23:52:03.631+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask insert_values_2
[2025-01-28T23:52:03.667+0000] {task_command.py:467} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_2 manual__2025-01-28T23:52:01.779071+00:00 [running]> on host 6b2a71fc0c6d
[2025-01-28T23:52:03.737+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='insert_values_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T23:52:01.779071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T23:52:01.779071+00:00'
[2025-01-28T23:52:03.738+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T23:52:03.746+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO users (id, name, age) VALUES
                (6, 'Harry', 49),
                (7, 'Nancy', 52),
                (8, 'Elvis', 26),
                (9, 'Mia', 20);
        
[2025-01-28T23:52:03.753+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-28T23:52:03.761+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-28T23:52:03.764+0000] {sql.py:553} INFO - Running statement: 
            INSERT INTO users (id, name, age) VALUES
                (6, 'Harry', 49),
                (7, 'Nancy', 52),
                (8, 'Elvis', 26),
                (9, 'Mia', 20);
        , parameters: None
[2025-01-28T23:52:03.766+0000] {sql.py:562} INFO - Rows affected: 4
[2025-01-28T23:52:03.778+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T23:52:03.779+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_2, run_id=manual__2025-01-28T23:52:01.779071+00:00, execution_date=20250128T235201, start_date=20250128T235203, end_date=20250128T235203
[2025-01-28T23:52:03.803+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T23:52:03.823+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-28T23:52:03.826+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
