[2025-01-29T00:01:44.139+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T00:01:44.153+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2025-01-29T00:01:42.566943+00:00 [queued]>
[2025-01-29T00:01:44.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2025-01-29T00:01:42.566943+00:00 [queued]>
[2025-01-29T00:01:44.163+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T00:01:44.183+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_values_1> on 2025-01-29 00:01:42.566943+00:00
[2025-01-29T00:01:44.189+0000] {standard_task_runner.py:72} INFO - Started process 1329 to run task
[2025-01-29T00:01:44.191+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_1', 'manual__2025-01-29T00:01:42.566943+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpq9fz7kfw']
[2025-01-29T00:01:44.192+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask insert_values_1
[2025-01-29T00:01:44.234+0000] {task_command.py:467} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_1 manual__2025-01-29T00:01:42.566943+00:00 [running]> on host 6b2a71fc0c6d
[2025-01-29T00:01:44.296+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='insert_values_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T00:01:42.566943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T00:01:42.566943+00:00'
[2025-01-29T00:01:44.298+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T00:01:44.306+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO users (name, age, is_active) VALUES
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        
[2025-01-29T00:01:44.313+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-29T00:01:44.321+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-29T00:01:44.325+0000] {sql.py:553} INFO - Running statement: 
            INSERT INTO users (name, age, is_active) VALUES
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        , parameters: None
[2025-01-29T00:01:44.327+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.NotNullViolation: null value in column "id" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (null, Julie, 30, null, f, 2025-01-29 00:01:44.326443).

[2025-01-29T00:01:44.334+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=executing_sql_pipeline, task_id=insert_values_1, run_id=manual__2025-01-29T00:01:42.566943+00:00, execution_date=20250129T000142, start_date=20250129T000144, end_date=20250129T000144
[2025-01-29T00:01:44.346+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T00:01:44.347+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task insert_values_1 (null value in column "id" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (null, Julie, 30, null, f, 2025-01-29 00:01:44.326443).
; 1329)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.NotNullViolation: null value in column "id" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (null, Julie, 30, null, f, 2025-01-29 00:01:44.326443).

[2025-01-29T00:01:44.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-29T00:01:44.381+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T00:01:44.387+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
