[2025-01-29T16:25:26.527+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T16:25:26.546+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-29T16:25:26.555+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-29T16:25:26.557+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T16:25:26.571+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-01-24 00:00:00+00:00
[2025-01-29T16:25:26.579+0000] {standard_task_runner.py:72} INFO - Started process 1604 to run task
[2025-01-29T16:25:26.583+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpx417759x']
[2025-01-29T16:25:26.586+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask taskBranch
[2025-01-29T16:25:26.638+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-24T00:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T16:25:26.732+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-01-29T16:25:26.734+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T16:25:26.747+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-29T16:25:26.761+0000] {python.py:240} INFO - Done. Returned value was: taskD
[2025-01-29T16:25:26.762+0000] {branch.py:38} INFO - Branch into taskD
[2025-01-29T16:25:26.763+0000] {skipmixin.py:230} INFO - Following branch ('taskD',)
[2025-01-29T16:25:26.774+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1), ('taskC', -1)]
[2025-01-29T16:25:26.811+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T16:25:26.812+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-01-24T00:00:00+00:00, execution_date=20250124T000000, start_date=20250129T162526, end_date=20250129T162526
[2025-01-29T16:25:26.836+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T16:25:26.860+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T16:25:26.866+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
