[2025-01-28T23:28:13.073+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T23:28:13.086+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.display_result manual__2025-01-28T23:28:10.482237+00:00 [queued]>
[2025-01-28T23:28:13.091+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.display_result manual__2025-01-28T23:28:10.482237+00:00 [queued]>
[2025-01-28T23:28:13.094+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T23:28:13.104+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): display_result> on 2025-01-28 23:28:10.482237+00:00
[2025-01-28T23:28:13.110+0000] {standard_task_runner.py:72} INFO - Started process 847 to run task
[2025-01-28T23:28:13.112+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'executing_sql_pipeline', 'display_result', 'manual__2025-01-28T23:28:10.482237+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpclw5piea']
[2025-01-28T23:28:13.114+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask display_result
[2025-01-28T23:28:13.144+0000] {task_command.py:467} INFO - Running <TaskInstance: executing_sql_pipeline.display_result manual__2025-01-28T23:28:10.482237+00:00 [running]> on host 6b2a71fc0c6d
[2025-01-28T23:28:13.198+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='display_result' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T23:28:10.482237+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T23:28:10.482237+00:00'
[2025-01-28T23:28:13.199+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T23:28:13.206+0000] {sql.py:278} INFO - Executing: SELECT * FROM users;
[2025-01-28T23:28:13.212+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-28T23:28:13.219+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-01-28T23:28:13.222+0000] {sql.py:553} INFO - Running statement: SELECT * FROM users;, parameters: None
[2025-01-28T23:28:13.223+0000] {sql.py:562} INFO - Rows affected: 9
[2025-01-28T23:28:13.240+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T23:28:13.241+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=display_result, run_id=manual__2025-01-28T23:28:10.482237+00:00, execution_date=20250128T232810, start_date=20250128T232813, end_date=20250128T232813
[2025-01-28T23:28:13.287+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T23:28:13.300+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T23:28:13.304+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
