[2025-01-29T16:25:26.528+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T16:25:26.546+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-01-29T16:25:26.555+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-01-29T16:25:26.557+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T16:25:26.572+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-01-28 00:00:00+00:00
[2025-01-29T16:25:26.579+0000] {standard_task_runner.py:72} INFO - Started process 1605 to run task
[2025-01-29T16:25:26.582+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmprpvb6fg9']
[2025-01-29T16:25:26.585+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask taskBranch
[2025-01-29T16:25:26.636+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-01-28T00:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T16:25:26.731+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-01-29T16:25:26.733+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T16:25:26.746+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-29T16:25:26.762+0000] {python.py:240} INFO - Done. Returned value was: taskC
[2025-01-29T16:25:26.763+0000] {branch.py:38} INFO - Branch into taskC
[2025-01-29T16:25:26.764+0000] {skipmixin.py:230} INFO - Following branch ('taskC',)
[2025-01-29T16:25:26.778+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1)]
[2025-01-29T16:25:26.813+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T16:25:26.814+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250129T162526, end_date=20250129T162526
[2025-01-29T16:25:26.837+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T16:25:26.870+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T16:25:26.874+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
